# Homebrew
tap "homebrew/bundle"       # Bundle Brewfile

# Applications
cask "arc"                  # Chromium based browser
cask "firefox"              # Web browse
cask "google-chrome"        # Web browser
cask "kitty"                # GPU-based terminal emulator
cask "postman"              # Collaboration platform for API development
cask "raycast"              # Control your tools with a few keystrokes
cask "spotify"              # Music streaming service
cask "visual-studio-code"   # Open-source code editor

# Tools
brew "aria2"                # Download with resuming and segmented downloading
brew "curl"                 # Get a file from an HTTP, HTTPS or FTP server
brew "gh"                   # GitHub command-line tool
brew "lazygit"              # Simple terminal UI for git commands
brew "mas"                  # Mac App Store command-line interface
brew "mise"                 # Polyglot runtime manager (asdf rust clone)
brew "stow"                 # Organize software neatly under a single directory tree (e.g. /usr/local)
brew "tree"                 # Display directories as trees (with optional color/HTML output)
brew "vercel-cli"           # Command-line interface for Vercel
brew 'watchman'             # Watch files and take action when they change 
brew "xcodes"               # Best command-line tool to install and switch between multiple versions of Xcode

# Optional
# cask "figma"                # Collaborative interface design tool
# mas "Slack", id: 803453959  # Team communication and collaboration software
# mas "Xcode", id: 497799835  # Developer tools
