#!/bin/sh

# Autoload vcs and colors
autoload -Uz colors && colors
autoload -Uz vcs_info

# Add a function to check for untracked files in the directory
# From https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples
+vi-git-untracked() {
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        # Show the marker if there are any untracked files in the repo
        # If you want to show the marker only for untracked files in $PWD, use:
        # [[ -n $(git ls-files --others --exclude-standard) ]] ; then
        hook_com[staged]+='!' # signify new files with a bang
    fi
}

# Enable only git for vcs_info
zstyle ':vcs_info:*' enable git 

# Format the main prompt for hostname, current folder, and permissions
PROMPT="%B%{$fg[yellow]%}%{$reset_color%}"
PROMPT+="\$vcs_info_msg_0_ "

# Setup a hook that runs before every prompt
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

# Style configurations for vcs_info
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
zstyle ':vcs_info:git:*' formats " %{$fg[blue]%}(%{$fg[red]%}%m%u%c%{$fg[yellow]%}%{$fg[magenta]%} %b%{$fg[blue]%})"
